### ISSUE TITLE
Show feed using Javascript without API not working / Version 2.1.1

### ISSUE THREAD

**Issue by josephkazarian** [nitsan-technologies/ns_instagram#13]
After upgrading to the version 2.1.1 the extension only works with Basic Display API.
The problem with Basic Display API that the max pictures to be shown is not settable.

When choosing "Show feed using Javascript without API" nothing is showing.
I tried downgrading to version 2.1.0 but it also didn't work.

On 2.0.0 it works completly perfectly.

**Comment by nitsan-technologies** [comment]
Dear @josephkazarian 

We appreciate your reported issues, Just fixed and released new v2.2.0 :)

Cheers,
Sanjay
