### ISSUE TITLE
Use variable [HTTP][proxy] from Typo3 Configuration Install Options

### ISSUE THREAD

**Issue by bkraut139** [nitsan-technologies/ns_instagram#14]
We have one problem. Our typo3 instance uses a proxy for internet access. Without a proxy, we can't access api.instagram.com and our feed is not displayed

In typo3 Configuration Install Options there is a variable [HTTP] [proxy]. Please use this variable in function file_get_contents (InstagramFeedsController.php) as an additional parameter.

**Comment by nitsan-technologies** [comment]
Dear @bkraut139 

We appreciate your feedback, Indeed Proxy-support is a bit important. Good news for you, we have released v2.2.1 with TYPO3 core's native HTTP PROXY support, Grab the latest version from https://extensions.typo3.org/extension/ns_instagram

Feel free to connect with us for any further request, feedback or suggestion to keep improve this extension, Thank you very much!

Cheers,
Team NITSAN
