### ISSUE TITLE
Post Previews aren't showing in admin

### ISSUE THREAD

**Issue by bsgdigital** [nitsan-technologies/ns_instagram#15]
Since Facebook deprecated https://api.instagram.com/oembed/ endpoint on Oct 22, post previews aren't visible in admin anymore - JS console shows 400 Status Code responses for all requests to https://api.instagram.com/oembed/?url=http://instagr.am/p/{POSTID}/

**Comment by nitsan-technologies** [comment]
Hello @bsgdigital 
Greetings of the day!

Thanks for the message.

Yes, you are right, The has deprecated the https://api.instagram.com/oembed/ endpoint on Oct 22, 2020.

So we request you to use the Instagram Basic API Display API to show the Instagram feed. Please find the documentation here: https://docs.t3terminal.com/en/latest/ExtNsInstagram/Configuration/Index.html#configure-global-settings

Please let's know if you need any further support on this from our side.

Thanks!
Team NITSAN
