### ISSUE TITLE
No Images with " Instagram Feed using Javascript "

### ISSUE THREAD

**Issue by nwMarcS** [nitsan-technologies/ns_instagram#18]
hy,

at your website https://demo.t3terminal.com/t3t-extensions/instagram the images are missing at the "Instagram Feed using Javascript" - it will just show the alternative text of the images.

There is a src attribute

`<img src="https://scontent-arn2-1.cdninstagram.com/v/t51.2885-15/e15/c257.0.565.565a/186255468_136562771847235_6995970805070771430_n.jpg?tp=1&amp;_nc_ht=scontent-arn2-1.cdninstagram.com&amp;_nc_cat=107&amp;_nc_ohc=EjSBaPJC5rcAX_53m5y&amp;edm=ABfd0MgBAAAA&amp;ccb=7-4&amp;oh=804575f24848c8eff0dfb4e6664302fb&amp;oe=60C7BFAB&amp;_nc_sid=7bff83" alt="We appreciate ... `

the correct src for this example would be:

`https://scontent-arn2-1.cdninstagram.com/v/t51.2885-15/e15/c257.0.565.565a/186255468_136562771847235_6995970805070771430_n.jpg?tp=1&_nc_ht=scontent-arn2-1.cdninstagram.com&_nc_cat=107&_nc_ohc=EjSBaPJC5rcAX_53m5y&edm=ABfd0MgBAAAA&ccb=7-4&oh=804575f24848c8eff0dfb4e6664302fb&oe=60C7BFAB&_nc_sid=7bff83`

**Comment by nitsan-technologies** [comment]
Hello @nwMarcS 
Greetings of the day!

Thanks for the message.

FYI, Facebook has deprecated the https://api.instagram.com/oembed/ endpoint on Oct 22, 2020, So all post previews aren't visible anymore. It will show 400 Status Code in the console.
So we request you to use the Instagram Basic API Display API to show the Instagram feed. Please find the documentation here: https://docs.t3terminal.com/en/latest/ExtNsInstagram/Configuration/Index.html#configure-global-settings

Please let's know if you need any further support on this from our side.

Thanks!
Team NITSAN
