### ISSUE TITLE
API Error: API doesn't get any media from Instagram. Make sure you have posted media on Instagram."

### ISSUE THREAD

**Issue by nitsan-technologies** [nitsan-technologies/ns_instagram#21]
Hello,
from a few days I'm having an error using the Instagram Plugin:
"API doesn't get any media from Instagram. Make sure you have posted media on Instagram."

I did a lot of test and check, but no luck.
I realized that your demo has the same error: https://demo.t3planet.com/t3-extensions/instagram

I think something changed on Instagram API. Could you please release and update?

**Comment by GiuseppeP** [comment]
Hello,
I did some test and looks like this PR could be a valid workaround for the issue:

#22

**Comment by dreadfulgate** [comment]
Thanks, exactly what I needed. 

In case somebody else is looking for this: In one of my installations, the deprecated line resulted in a Typo3 exception (#1476107295).

**Comment by nitsan-technologies** [comment]
Hey Everyone!

Good news! We have just released https://github.com/nitsan-technologies/ns_instagram/releases/tag/3.0.4

@GiuseppeP We appreciate your contribution.

Cheers, Team NITSAN
