### ISSUE TITLE
Multiple includes of CSS

### ISSUE THREAD

**Issue by sgrossberndt** [nitsan-technologies/ns_instagram#3]
https://github.com/nitsan-technologies/ns_instagram/blob/03b9a6a6a1a846a1734537d40e9463a0a0a131a5/Classes/Controller/FeedController.php#L57

Just by looking at the code - if there are two list plugins on one page - wouldn't everything you add to the pagerenderer (js/css) be added twice? Use an additional static TypoScript file to be included by the user instead

**Comment by nitsan-technologies** [comment]
Hey @sgrossberndt 

We have just published a new version of this extension at TER.
URL: https://extensions.typo3.org/extension/ns_instagram
T3terminal: https://t3terminal.com/instagram-typo3-extension-free

We have done the major changes in it.
Have a look at it and share your feedback with us.

Cheers!
Team NITSAN
