### ISSUE TITLE
Stopped working.

### ISSUE THREAD

**Issue by konfuzius** [nitsan-technologies/ns_instagram#5]
ns_instagram v1.0.0
typo3 v8.7.8

Console:
GET https://api.instagram.com/v1/users//media/recent?access_token=xxxxxxxxxxxxxxxxxxxxxxx&count=33&callback=jQuery321016335709112533126_1521728878604&_=1521728878605 net::ERR_ABORTED

Please update your extension.
Thanks.

**Comment by nitsan-technologies** [comment]
Hello @konfuzius 

We have checked out this issue and we have found that Instagram made some changes related to API.
So current version of Instagram not working properly. We will upgrade it and relaunch it soon at TER.

Thank you very much for your time :)

**Comment by nitsan-technologies** [comment]
Hello @konfuzius 

We have made some changes according to latest Instagram API at this repository.
So, please download latest changes from this repository and share your thought for the same.

Have a great day ahead :)

Thanks!
