### ISSUE TITLE
Call to undefined method TYPO3\CMS\Core\Error\Exception::getResponse()

### ISSUE THREAD

**Issue by IL-Michi** [nitsan-technologies/ns_instagram#8]
If got an error on typo3conf/ext/ns_instagram/Classes/Controller/PhotoTileController.php in line 113.
Call to undefined method TYPO3\CMS\Core\Error\Exception::getResponse()

I've integrated everything as it says in the instructions.

**Comment by markustobler** [comment]
+1

**Comment by nitsan-technologies** [comment]
Hey @IL-Michi & @markustobler  

We have just published a new version of this extension at TER.
URL: https://extensions.typo3.org/extension/ns_instagram
T3terminal: https://t3terminal.com/instagram-typo3-extension-free

We have done the major changes in it.
Have a look at it and share your feedback with us.

Cheers!
Team NITSAN
