### ISSUE TITLE
Too few arguments to function GuzzleHttp\Psr7\Response::getHeader()

### ISSUE THREAD

**Issue by besttycho** [nitsan-technologies/ns_instagram#9]
Too few arguments to function GuzzleHttp\Psr7\Response::getHeader(), 0 passed in ns_instagram/Classes/Controller/FeedController.php on line 206 and exactly 1 expected 
00206:         $header = $response->getHeader();

**Comment by nitsan-technologies** [comment]
Hey @besttycho 

We have just published a new version of this extension at TER.
URL: https://extensions.typo3.org/extension/ns_instagram
T3terminal: https://t3terminal.com/instagram-typo3-extension-free

We have done the major changes in it.
Have a look at it and share your feedback with us.

Cheers!
Team NITSAN
